"""Independent tranche31 connection tests on finite synthetic inputs.
No rules are changed. W2 uses the submitted test-only mean-distance fixture.
A local pickle cache is optional and must have been generated by setup.py here;
no pickle cache is shipped. Production arrays / official OT are not exercised.
"""
import os,sys,copy,pickle,hashlib
from pathlib import Path
ROOT=Path(os.environ.get('PHASEB_ROOT',Path(__file__).resolve().parents[1]))
sys.path[:0]=[str(ROOT),str(ROOT/'tests')]
import numpy as np
import pytest
from runner_fixture import build_fixture,family_cases
from audit_fixture30 import diagnostic_cases,negative_context
from step1_engine.integrated_runner import run_first_wave,RunManifest,assemble_parent
from step1_engine.archive import Archive,ArchiveRef,resolve_transition_archive
from step1_engine.stage12 import StageTransition
from step1_engine.orchestrator import evaluate_family_staged
from step1_engine import orchestrator as orch
from step1_engine import serialization as ser

@pytest.fixture(scope='module')
def base():
    cache=os.environ.get('AUDIT31_LOCAL_CACHE')
    if cache:
        with open(cache,'rb') as h:return pickle.load(h)
    f=build_fixture();f['ctx'].results={};f['ctx'].validate();return f

@pytest.fixture(scope='module')
def negative(base):
    cache=os.environ.get('AUDIT31_NEGATIVE_CACHE')
    if cache:
        with open(cache,'rb') as h:return pickle.load(h)
    return negative_context(base)

def run(f,path,**kw):
    opts=dict(t_target=(80.,400.),pseudo_T1=[80.],pseudo_T2=[400.],mode='smoke');opts.update(kw)
    a=Archive(str(path));r=run_first_wave(f['reg'],f['man'],f['cases'],f['ctx'],f['ctx'].context_sha256,archive=a,**opts)
    return r,a

def parent_result(r,a,family='E7'):
    return a.get(ArchiveRef(**r.archive_refs['family_core:'+family]))

def source(r,a,key):return a.get(ArchiveRef(**r.cases[key]['result_ref']))

def assert_derivation(f,r,a,family='E7'):
    parent=parent_result(r,a,family)
    for key,(fm,fn,pmap) in f['cases'].items():
        if fm.family!=family:continue
        rec=source(r,a,key)
        assert rec['kind']=='case_position_record'
        assert rec['truths']==parent['truths']
        assert rec['precision']==parent['precision']
        assert rec['decision']['technical_status']==parent['decision']['technical_status']
        assert rec['decision']['display_label']==parent['decision']['display_label']
        assert rec['evidence']['parent_family_result']=='family_core:'+family
        if family=='E1':
            assert rec['evidence']['position_probabilities']=={}
            continue
        for eid,pos in pmap.items():
            p=rec['evidence']['position_probabilities'][pos];d=parent['per_config'][eid]
            assert p==dict(P=d['P_model'],hits=d['hits_M'],N=d['N'],precision=d['precision']['state'],stage=d['stage'])
            c=next(c for c in fm.configs if c.evaluation_id==eid);n=p['N']
            hits=int(np.count_nonzero((c.T1_model[:n]<=80.)&(c.T2_model[:n]<=400.)))
            assert hits==p['hits'] and p['P']==hits/n

@pytest.fixture(scope='module')
def normal(base,tmp_path_factory):
    f=copy.deepcopy(base);r,a=run(f,tmp_path_factory.mktemp('normal31'))
    return f,r,a

@pytest.fixture(scope='module')
def diagnostic(base,negative,tmp_path_factory):
    f=dict(reg=base['reg'],man=base['man'],cases=diagnostic_cases(base['reg'],base['man']),ctx=negative)
    r,a=run(f,tmp_path_factory.mktemp('diagnostic31'));return f,r,a

@pytest.fixture(scope='module')
def required_tech(base,negative,tmp_path_factory):
    f=dict(reg=base['reg'],man=base['man'],cases=diagnostic_cases(base['reg'],base['man'],all_sizes_need_ci=True),ctx=negative)
    r,a=run(f,tmp_path_factory.mktemp('required31'));return f,r,a

def test_position_record_probabilities_reproduce_parent_and_literal_hits(normal):
    f,r,a=normal;assert_derivation(f,r,a)

def test_position_records_carry_parent_truths_not_case_core_truths(diagnostic):
    f,r,a=diagnostic;assert_derivation(f,r,a)
    c=r.cases['E7/L1.00'];pos=source(r,a,'E7/L1.00');diag=a.get(ArchiveRef(**c['diagnostic_ref']))
    assert pos['truths']['support'] is True
    assert diag['decision']['technical_status']=='technical_fail'
    assert pos['decision']['technical_status']=='ok'

def test_singular_diagnostic_replicates_remain_recorded_without_primary_veto(diagnostic):
    f,r,a=diagnostic
    d=a.get(ArchiveRef(**r.cases['E7/L1.00']['diagnostic_ref']))
    assert d['logD']['ci']['counts']=={'finite':28,'technical_invalid':2}
    assert d['logD']['ci']['math_state']=='technical_fail'
    assert r.families['E7']['status']=='final at 3 positions'
    assert r.calibration['support']['truths']==[True]
    assert parent_result(r,a)['logD']['ci'] is None

def test_necessary_parent_ci_tech_reaches_all_case_sources(required_tech):
    f,r,a=required_tech;assert_derivation(f,r,a)
    assert parent_result(r,a)['decision']['technical_status']=='technical_fail'
    for k in r.cases:
        assert source(r,a,k)['decision']['technical_status']=='technical_fail'
        assert source(r,a,k)['position_status']['state']=='technical_fail'
    assert r.calibration['support']['summary']['status']=='technical_fail'
    assert r.final_label_released is False

def test_normal_reopened_run_resolves_position_parent_and_diagnostic_links(normal):
    f,r,old=normal;a=Archive(old.root)
    body=a.get(ArchiveRef(**r.binding['run_manifest_ref']));restored=RunManifest(**body)
    for k,c in restored.cases.items():
        tr=StageTransition(**restored.families[c['family']]['transitions'][c['size_id']])
        rec=resolve_transition_archive(a,tr,ArchiveRef(**c['result_ref']))
        parent_key=rec['evidence']['parent_family_result']
        p=a.get(ArchiveRef(**restored.archive_refs[parent_key]))
        d=a.get(ArchiveRef(**rec['evidence']['diagnostic_ref']))
        assert p['family']==rec['family']==d['family']
        assert d['size_id']==rec['size_id']
        assert rec['decision']['technical_status']==p['decision']['technical_status']
    assert restored.payload_sha()==r.payload_sha()==r.binding['run_manifest_sha256']
    assert a.verify_all()['ok']

def test_local_edit_of_decoded_diagnostic_does_not_change_parent_or_case(normal):
    f,r,a=normal;k='E7/L1.00'
    p=ser.dumps(parent_result(r,a));s=ser.dumps(source(r,a,k))
    d=a.get(ArchiveRef(**r.cases[k]['diagnostic_ref']))
    d['truths']['support']=not bool(d['truths']['support'])
    d['per_config'].clear()
    assert ser.dumps(parent_result(r,a))==p and ser.dumps(source(r,a,k))==s

def test_pseudo_values_recover_bit_exactly_with_matching_array_hashes(base,tmp_path):
    f=copy.deepcopy(base);x=np.array([80.125,81.375,83.625]);y=np.array([400.0625,401.5625,412.5])
    r,a=run(f,tmp_path,pseudo_T1=x,pseudo_T2=y)
    persisted=a.get(ArchiveRef(**r.binding['run_manifest_ref']))['thresholds']['pseudo']
    assert persisted['dtype']=='float64' and persisted['n']==3 and persisted['shape']==[3]
    for name,expected in [('T1',x),('T2',y)]:
        recovered=np.asarray(persisted[name],dtype=np.float64)
        assert recovered.tobytes()==expected.tobytes()
        assert hashlib.sha256(recovered.tobytes()).hexdigest()==persisted['sha256_'+name]

def test_all_native_absent_keeps_matched_only_results_explicit(base,tmp_path):
    f=copy.deepcopy(base);f['cases']={k:(fm,None,p) for k,(fm,fn,p) in f['cases'].items()}
    r,a=run(f,tmp_path)
    assert parent_result(r,a)['native'] is None
    for k in r.cases:
        diag=a.get(ArchiveRef(**r.cases[k]['diagnostic_ref']))
        assert diag['native'] is None
    assert r.final_label_released is False

def test_e1_position_branch_is_exempt_and_parent_is_preserved(base,tmp_path):
    f=copy.deepcopy(base);f['cases']=family_cases(f['reg'],f['man'],'E1')
    r,a=run(f,tmp_path);assert_derivation(f,r,a,'E1')
    assert r.families['E1']['status']=='exempt (observer-homogeneous)'
    for k in r.cases:
        s=source(r,a,k)
        assert s['evidence']['w2_context'] is None
        assert s['position_status']['w2_trigger'] is None

def test_e1_required_parent_tech_is_not_exempted(base,tmp_path,monkeypatch):
    f=copy.deepcopy(base);f['cases']=family_cases(f['reg'],f['man'],'E1')
    original=orch._stage_selection
    def failure(fam,t1,t2):
        sel=original(fam,t1,t2)
        if fam.family=='E1' and len(fam.configs)==3:
            sel['technical']=True;sel['N0']['precision']['state']='technical_fail'
        return sel
    monkeypatch.setattr(orch,'_stage_selection',failure)
    r,a=run(f,tmp_path)
    assert r.families['E1']['status']=='technical_fail'
    assert r.calibration['support']['summary']['status']=='technical_fail'
    for k,c in r.cases.items():
        tr=StageTransition(**r.families['E1']['transitions'][c['size_id']])
        rec=resolve_transition_archive(a,tr,ArchiveRef(**c['result_ref']))
        assert tr.phase=='technical_fail' and rec['decision']['technical_status']=='technical_fail'

def test_pseudo_and_primary_scope_is_not_claimed_as_complete_calibration(normal):
    f,r,a=normal
    assert r.final_label_released is False
    for lvl in ['support','strong']:
        assert '12-position stage not integrated' in r.calibration[lvl]['summary']['reason']
        assert 'NOT the registered family calibration' in r.calibration[lvl]['any_case_core_diagnostic']['summary']['reason']

def test_source_reference_and_diagnostic_reference_are_not_interchanged(normal):
    f,r,a=normal
    for k,c in r.cases.items():
        p=a.get(ArchiveRef(**c['result_ref']));d=a.get(ArchiveRef(**c['diagnostic_ref']))
        assert c['result_ref']['kind']=='three_position_result'
        assert c['diagnostic_ref']['kind']=='family_result'
        assert p['kind']=='case_position_record' and 'per_config' not in p
        assert 'per_config' in d
        assert p['evidence']['diagnostic_ref']==c['diagnostic_ref']
