"""Tranche 30 targeted contracts. Run with PHASEB_ROOT=/path/to/phaseB.
No runtime source, rules, verdicts, or numerical functions are replaced.
The pseudo-persistence test accepts the exact columns anywhere in retrievable
JSON records rather than requiring a proposed new API or field name.
"""
import os,sys,copy,hashlib,pickle
from pathlib import Path
ROOT=Path(os.environ.get('PHASEB_ROOT',Path(__file__).resolve().parents[1]))
sys.path[:0]=[str(ROOT),str(ROOT/'tests'),str(Path(__file__).parent)]
import numpy as np
import pytest
from step1_engine.integrated_runner import assemble_parent,run_first_wave,RunManifest
from step1_engine.archive import Archive,ArchiveRef,resolve_transition_archive
from step1_engine.stage12 import StageTransition
from step1_engine.orchestrator import evaluate_family_staged
from step1_engine.formal_runner import input_fingerprint
from step1_engine.errors import InputContractError
from step1_engine import serialization as ser
from runner_fixture import build_fixture
from audit_fixture30 import diagnostic_cases,negative_context

@pytest.fixture(scope='module')
def base():
    # Optional cache is generated by this audit; never load untrusted pickle.
    cache=os.environ.get('AUDIT30_FIXTURE_CACHE')
    if cache:
        with open(cache,'rb') as h:return pickle.load(h)
    f=build_fixture();f['ctx'].results={};f['ctx'].validate();return f

@pytest.fixture(scope='module')
def negative(base):return negative_context(base)

def parents(f):
    return assemble_parent(f['reg'],f['man'],'E7',{k.split('/')[1]:(v[0],v[1]) for k,v in f['cases'].items()})

def run(f,path,**kw):
    arc=Archive(str(path));opts=dict(t_target=(80.,400.),pseudo_T1=[80.],pseudo_T2=[400.],mode='smoke');opts.update(kw)
    r=run_first_wave(f['reg'],f['man'],f['cases'],f['ctx'],f['ctx'].context_sha256,archive=arc,**opts)
    return r,arc

@pytest.fixture(scope='module')
def normal(base,tmp_path_factory):
    f=copy.deepcopy(base);r,a=run(f,tmp_path_factory.mktemp('normal30'));return f,r,a

def test_parent_contains_all_sizes_with_registered_weights(base):
    f=copy.deepcopy(base);p,n=parents(f)
    assert p.grid_identity['sizes']==f['reg'].surviving['E7']
    assert len(p.configs)==len(n.configs)==9
    assert all(c.weight==pytest.approx(1/9) for c in p.configs+n.configs)
    assert all(c.weight==pytest.approx(1/3) for fm,fn,_ in f['cases'].values() for c in fm.configs+fn.configs)

@pytest.mark.parametrize('size',['L1.00','L1.20','L1.50'])
def test_partial_native_is_rejected_instead_of_dropping_supplied_sizes(base,size):
    f=copy.deepcopy(base);key='E7/'+size;fm,fn,pm=f['cases'][key];f['cases'][key]=(fm,None,pm)
    with pytest.raises(InputContractError):parents(f)

def test_explicit_all_native_absent_remains_supported(base):
    f=copy.deepcopy(base);f['cases']={k:(fm,None,p) for k,(fm,fn,p) in f['cases'].items()}
    pm,pn=parents(f);assert pn is None and len(pm.configs)==9

def test_case_dictionary_order_does_not_change_parent_fingerprints(base):
    a=copy.deepcopy(base);b=copy.deepcopy(base);b['cases']=dict(reversed(list(b['cases'].items())))
    assert [input_fingerprint(x) for x in parents(a)]==[input_fingerprint(x) for x in parents(b)]

def test_missing_surviving_size_is_rejected(base):
    f=copy.deepcopy(base);f['cases'].pop('E7/L1.20')
    with pytest.raises(InputContractError):parents(f)

def test_require_all_families_rejects_partial_family_run(base,tmp_path):
    with pytest.raises(InputContractError):run(copy.deepcopy(base),tmp_path,require_all_families=True)

def test_normal_sources_are_resolvable_with_transitions(normal):
    f,r,a=normal
    for k,c in r.cases.items():
        tr=StageTransition(**r.families['E7']['transitions'][c['size_id']])
        source=resolve_transition_archive(a,tr,ArchiveRef(**c['result_ref']))
        assert source['family']=='E7' and source['size_id']==c['size_id']

def test_run_payload_and_file_sha_have_consistent_separate_roles(normal):
    f,r,a=normal;ref=ArchiveRef(**r.binding['run_manifest_ref']);saved=a.get(ref);restored=RunManifest(**saved)
    assert ref.sha256==r.binding['run_manifest_file_sha256']
    assert r.payload_sha()==restored.payload_sha()==r.binding['run_manifest_sha256']

def test_generated_twelve_bodies_are_preserved(normal):
    f,r,a=normal
    for s,sha in r.families['E7']['required_manifests'].items():
        ref=ArchiveRef(**r.archive_refs['twelve_manifest:E7/'+s]);body=a.get(ref)
        assert body['sha256']==sha and len(body['points'])==12

def test_case_only_diagnostic_ci_failure_does_not_poison_position(normal,negative,tmp_path):
    base,r,a=normal;f=dict(reg=base['reg'],man=base['man'],ctx=negative,cases=diagnostic_cases(base['reg'],base['man']))
    parent=evaluate_family_staged(*parents(f),80.,400.)
    assert parent.truths['support'] is True and parent.logD['ci'] is None and parent.decision['technical_status']=='ok'
    per=evaluate_family_staged(*f['cases']['E7/L1.00'][:2],80.,400.)
    assert per.Q_ci_seed0['lower']>=10 and per.logD['ci']['math_state']=='technical_fail'
    result,arc=run(f,tmp_path)
    # Correct scientific case status comes from required Q+position checks,
    # not a logD CI needed only by a per-size diagnostic predicate.
    assert result.families['E7']['status']=='final at 3 positions'
    assert result.calibration['support']['truths']==[True]

def test_required_family_ci_failure_remains_technical(normal,negative,tmp_path):
    base,r,a=normal;f=dict(reg=base['reg'],man=base['man'],ctx=negative,cases=diagnostic_cases(base['reg'],base['man'],all_sizes_need_ci=True))
    parent=evaluate_family_staged(*parents(f),80.,400.)
    assert parent.Q_ci_seed0['lower']>=10 and parent.decision['technical_status']=='technical_fail'
    result,arc=run(f,tmp_path)
    assert result.families['E7']['status']=='technical_fail'
    assert result.calibration['support']['summary']['status']=='technical_fail'
    assert result.final_label_released is False

def vectors(x):
    if isinstance(x,list):
        if all(isinstance(v,(int,float)) and not isinstance(v,bool) for v in x):yield np.asarray(x,dtype=np.float64)
        for v in x:yield from vectors(v)
    elif isinstance(x,dict):
        for v in x.values():yield from vectors(v)

def test_exact_pseudo_thresholds_are_recoverable_from_archived_records(base,tmp_path):
    t1=np.array([80.125,81.375,83.625]);t2=np.array([400.0625,401.5625,412.5])
    r,a=run(copy.deepcopy(base),tmp_path,pseudo_T1=t1,pseudo_T2=t2)
    stored=[ser.from_jsonable(r.as_dict())]
    stored += [a.get(ArchiveRef(e['kind'],e['sha256'],e['path'],e['identity'])) for e in a._entries()]
    all_vectors=[v for rec in stored for v in vectors(rec)]
    # Complete 64-bit column recovery, not inversion of the SHA or assumption of
    # a particular field name. Full external-asset persistence is an alternative
    # design; it must provide an actual retrievable content reference, not just SHA.
    assert any(np.array_equal(v,t1) for v in all_vectors), 'only pseudo T1 SHA/shape/n saved; no retrievable values'
    assert any(np.array_equal(v,t2) for v in all_vectors), 'only pseudo T2 SHA/shape/n saved; no retrievable values'
